# Etapa de build con Node
FROM node:22-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# URL base del API en PRODUCCIÓN (API Gateway / servidor remoto)
ENV VITE_API_BASE_URL_PRODUCCION=https://fabrimine.com

ENV VITE_IMG_PREFIX=/publications_service

# Prefijo para imágenes de publicaciones
ENV VITE_IMG_PREFIX=/publications_service

# Google OAuth Client ID
ENV VITE_GOOGLE_CLIENT_ID=1050273557756-e77g4ejuckimmf3km8fmemhkue7hfr3a.apps.googleusercontent.com

ENV VITE_BCV_API=/bcv-api/

RUN npm run build

# Etapa de producción con Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf





